# air.toml

root = "."
tmp_dir = "tmp"
build_dir = "bin"

[build]
  binary_name = "main"
  ldflags = "-s -w"

  [build.gopack]
    import_path = "main"

[log]
  prefix = "air"
  level = "debug"
  output = "stdout"
